[package]
name = "config-checker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
resolver = "2"
description.workspace = true
readme.workspace = true
repository.workspace = true

[lib]


[dependencies]
colored = "3.0.0"
config-checker-macros = {path = "../macros", version = "*"}
